### ISSUE TITLE
Make init() private in the framework

### ISSUE THREAD

**Issue by zetasq** [teambition/WebBrowser#2]
App will crash if the user use the inherited init(). Make the init() private can fix this problem.

**Comment by hongxinhope** [comment]
@zetasq Many thanks for your Feedback!
This problem is fixed in [release 0.0.8](https://github.com/teambition/WebBrowser/releases/tag/0.0.8).
You can init WebBrowser like ```let webBrowserViewController = WebBrowserViewController()```, and it will not crash.
